### PR TITLE
Update to wlroots 0.16

### PR DESCRIPTION
**Pull request by godalming123**
**⚠️ This is a *massive* change and their are lots of things to note** - also @keshto if their are any big changes you want me to revert like using meson instead of make then I can do that.
# This includes
- Use meson instead of make
- Update to wlroots 0.16
- add a `.clang-format` file
- add a help message inside the compositor when you press just alt
- completely change the keybings
- much improved gtk popups
    - when you drag a popup instead it drags the parent
    - when you try to focus a popup the parent is brought to the front scene node
    - when a window has a popup you cannot focus its parent which forces you to see the popup
- add support for resizing/moving windows with alt + mouse
- add an implementation of drag icons although ⚠️ it sometimes make the compositor die (I have no idea why)
- add fullscreen windows
- add support for focusing the previous window *as well as* focusing the next
- add support for closing windows with the keyboard
- when a window is killed the next window in focus order is shown
- add libinput for pointers which allows for things like mouse acceleration
- add the virtual keyboard protocol (⚠️ this code is untested)
- the cursor now resets itself when a client is destroyed
- make the cursor appear onscreen without you needing to move the mouse
# ⚠️ there are some things that are in tinywl_plus 0.15 but not in my fork
- maximising windows
- server side decorations

### CODE REVIEW

**Comment by godalming123** [comment]
If anyone would like to learn how I implemented these things I suggest reading [here](https://github.com/godalming123/tinytile/commits/main) instead as each commit implements one small thing rather then this pr which is giant

**Comment by keshto** [comment]
Please follow the guidelines in the README. The idea is to have commits/patches than can be applied on to upstream tinywl. Each commit should be a feature. See the commit history of the current project for an idea.

Closing this as this is in no way shape or form following the above goals.

**Comment by godalming123** [comment]
I don't have the time to rebase the code to have each commit a feature although I've given you a repo so you can do that in your own time if you like

**Comment by godalming123** [comment]
I'm deleting the fork as it is kind of out of date with https://github.com/godalming123/tinytile which just works better

**Pull request closed without merging**
